version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - api

  api:
    container_name: api 
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spotify_queue
      - REDIRECT_URI=http://localhost:8000/api/v1/callback
      - CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  queue_manager:
      build:
        context: ./queue_manager
        dockerfile: Dockerfile
      volumes:
        - ./queue_manager:/app
      environment:
        - API_BASE_URL=http://api:8000/api/v1
      depends_on:
        - api
      networks:
        - app-network

  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotify_queue
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
    name: spotify_queue_postgres_data

networks:
  app-network:
    name: spotify_queue_network